extends RefCounted
const Wallet = preload("res://scripts/wallet.gd")
const Catalog = preload("res://scripts/catalog.gd")

static func run() -> void:
	const PATH = "user://qa-progression-wallet.cfg"
	Wallet.clear_profile(PATH)
	# A legacy coins-only save must survive the shop migration.
	var legacy := ConfigFile.new()
	legacy.set_value("wallet", "coins", 80)
	assert(legacy.save(PATH) == OK)
	var wallet := Wallet.new(PATH)
	assert(wallet.balance == 80 and wallet.owned.is_empty())
	assert(Catalog.CHARACTERS.filter(func(entry): return entry.price == 0).size() == 2)
	assert(wallet.owns_character("pikachu") and wallet.owns_character("yablochko"))
	assert(not wallet.purchase_character("kirby") and wallet.balance == 80)
	assert(not wallet.purchase_character("unknown"))
	assert(wallet.purchase_character("zaichik") and wallet.balance == 30)
	assert(not wallet.purchase_character("zaichik") and wallet.balance == 30)
	assert(not wallet.purchase_character("pikachu") and wallet.balance == 30)
	wallet = Wallet.new(PATH)
	assert(wallet.owns_character("zaichik") and wallet.balance == 30)
	wallet.activate_double_coins()
	assert(wallet.double_remaining() >= 599 and wallet.double_remaining() <= 600)
	wallet = Wallet.new(PATH)
	assert(wallet.coin_multiplier() == 2 and wallet.double_remaining() <= 600)
	wallet.double_until = int(Time.get_unix_time_from_system()) - 1
	assert(wallet.coin_multiplier() == 1 and wallet.double_remaining() == 0)
	wallet.record_run("revived-run", 100, "pikachu")
	wallet.record_run("revived-run", 150, "pikachu")
	wallet.record_run("revived-run", 90, "pikachu")
	assert(wallet.records.size() == 1 and wallet.best_score() == 150)
	for i in range(15): wallet.record_run(str(i), i + 1, "yablochko")
	wallet = Wallet.new(PATH)
	assert(wallet.records.size() == 10 and wallet.best_score() == 150)
	assert(wallet.records.back().score == 7)
	# If the browser mirror could not update, a newer filesystem save must win.
	var newer := ConfigFile.new()
	assert(newer.load(PATH) == OK)
	newer.set_value("wallet", "revision", wallet.revision + 1)
	newer.set_value("wallet", "coins", 45)
	assert(newer.save(PATH) == OK)
	assert(Wallet.new(PATH).balance == 45)
	Wallet.clear_profile(PATH)
	print("SKYJUMP_PROGRESSION_OK migration purchases prices persistence timed_bonus records")
