name: Check local player
on:
  push:
    paths: ['tools/launcher/**', '.github/workflows/launcher.yml']
  pull_request:
    paths: ['tools/launcher/**', '.github/workflows/launcher.yml']
  workflow_dispatch:
permissions:
  contents: read
jobs:
  launcher:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4
        with:
          lfs: false
      - uses: actions/setup-go@40f1582b2485089dde7abd97c1529aa768e1baff # v5
        with:
          go-version: '1.27.1'
          cache: false
      - name: Check server and archive errors
        working-directory: tools/launcher
        run: go test -v ./...
